from selenium.webdriver.common.by import By


class AdminEventPageLocators:
    btn_generate_result_final = (By.XPATH, '//button[contains(., "Отправить") and @class="swal2-confirm swal2-styled"]')
    result_final = (By.CSS_SELECTOR, 'tbody > tr')
    event_festival_2024 = (By.XPATH, '//td[contains(.,"Фестиваль 2024")]/..//a[@class="grid-row-delete btn btn-xs btn-danger"]')
    event_festival_2024_yes = (By.XPATH, '//td[contains(.,"Фестиваль 2024")]/..//span[@class="bootstrap-switch-handle-on bootstrap-switch-success"]')
    event_festival_2024_no = (By.XPATH, '//td[contains(.,"Фестиваль 2024")]/..//span[@class="bootstrap-switch-handle-off bootstrap-switch-default"]')
    event_competition_yes = (By.XPATH, '//td[contains(.,"competition")]/..//span[@class="bootstrap-switch-handle-on bootstrap-switch-success"]')
    event_competition_no = (By.XPATH, '//td[contains(.,"competition")]/..//span[@class="bootstrap-switch-handle-off bootstrap-switch-default"]')
    nav_pay = (By.XPATH, '//span[contains(text(), "Оплата за сервис")]')
    is_semifinal = (By.XPATH, '(//div[@id="is_semifinal"])[1]')
    is_not_semifinal = (By.XPATH, '(//div[@id="is_semifinal"])[2]')
    title_final = (By.XPATH, '//a[contains(text(), "Карточки для финалистов")]')
    nav_final = (By.XPATH, '//span[contains(text(), "Финал")]')
    title_setting_routes = (By.XPATH, '//th[contains(text(), "Настройка трасс для соревнования")]')
    nav_setting_routes = (By.XPATH, '//span[contains(text(), "Настройка трасс")]')
    title_semifinal = (By.XPATH, '//a[contains(text(), "Карточки для полуфиналистов")]')
    nav_semifinal = (By.XPATH, '//span[contains(text(), "Полуфинал")]')
    title_qualification = (By.XPATH, '//a[contains(text(), " Сгенерировать участников [beta](Ожидание до ~ 2 мин)")]')
    nav_qualification = (By.XPATH, '//span[contains(text(), "Квалификация")]')
    title_events = (By.XPATH, '//a[contains(text(), " Уведомить по почте всех юзеров")]')
    nav_events = (By.XPATH, '//span[contains(text(), "Соревнования")]')
    title_pay = (By.XPATH, '//th[contains(text(), "Стартовый взнос")]')
    title_main = (By.XPATH, '//h3[contains(text(), "Кол-во участников")]')
    nav_main = (By.XPATH, '//span[contains(text(), "Главная")]')
    user_name = (By.CSS_SELECTOR, 'input[name="username"]')
    password = (By.CSS_SELECTOR, 'input[name="password"]')
    btn_submit = (By.ID, 'create-event')
    btn_enter = (By.CSS_SELECTOR, 'button[type="submit"]')
    btn_tab_pay = (By.CSS_SELECTOR, '[href="#tab-form-2"]')
    btn_tab_control = (By.CSS_SELECTOR, '[href="#tab-form-4"]')
    btn_tab_options = (By.CSS_SELECTOR, '[href="#tab-form-3"]')
    title_admin = (By.XPATH, '//*[contains(text(), "Мой сайт скалодром")]')
    title_success_create = (By.XPATH, '//div[contains(., "Успешно сохранено!")]')
    image = (By.CSS_SELECTOR, 'input[type="file"]')
    description_text_area = (By.XPATH, '//*[contains(@class, \'note-editable\')]')
    classic_radio_btn = (By.XPATH, '//*[contains(@class, "is_france_system_qualification0")]')
    france_system_radio_btn = (By.XPATH, '//*[contains(@class, "is_france_system_qualification1")]')
    all_route_radio_btn = (By.XPATH, '//div[contains(@class, \'mode2\')]')
    btn_add_category = (By.XPATH, "//div[contains(@class, 'categories-add')]")
    field_category_1 = (By.XPATH, "(//input[contains(@name, 'categories[values][]')])[1]")
    field_category_2 = (By.XPATH, "(//input[contains(@name, 'categories[values][]')])[2]")