from selenium.webdriver.common.by import By


class EventPageLocators:
    btn_edit_result = (By.XPATH, '//a[contains(., "Изменить результаты")]')
    btn_all_flash =(By.ID, 'all-flash')
    select_number_route_3 = (By.XPATH, '(//*[@id="show_final_route_id_1"])[2]')
    pop_up_select_route_index_1 = (By.XPATH, '//li[contains(text(), \'1\')]')
    pop_up_select_beginner_index_1 = (By.XPATH, '//li[contains(text(), \'Новичок\')]')
    pop_up_select_all_index_1 = (By.XPATH, '//li[contains(text(), \'Общий зачет\')]')
    select_participant = (By.XPATH, "(//span[contains(text(), 'Участник')])[1]")
    select_participant_3 = (By.XPATH, "(//span[contains(text(), 'Участник')])[3]")
    select_participant_4 = (By.XPATH, "(//span[contains(text(), 'Участник')])[4]")
    select_number_route = (By.XPATH, "(//span[contains(text(), 'Трасса')])[1]")
    select_number_route_2 = (By.XPATH, "(//span[contains(text(), 'Трасса')])[2]")
    select_sport_category = (By.ID, 'floatingSelectSportCategory')
    btn_main_info = (By.XPATH, '//button[contains(text(), \'Общая информация\')]')
    btn_sets = (By.XPATH, "//button[contains(., 'Сеты')]")
    btn_rules = (By.XPATH, '//button[contains(., \'Положение\')]')
    btn_price = (By.XPATH, '//button[contains(., \'Стартовый взнос\')]')
    btn_list_participant = (By.XPATH, '//a[contains(., \'Список участников\')]')
    btn_qualification_results = (By.XPATH, '//a[contains(., \'Предварительные результаты\')]')
    qualification_results = (By.XPATH, '//h5[contains(., \'Мужчины\')]')
    list_participants = (By.ID, 'borderedTabJustified')
    select_category = (By.ID, 'floatingSelectCategory')
    select_sets = (By.ID, 'floatingSelect')
    select_changed_sets = (By.ID, 'floatingSelectChangeSet')
    btn_change_set = (By.ID, 'btn-participant-change-set')
    btn_take_part = (By.ID, 'btn-participant')
    birthday = (By.ID, 'birthday')
    success_take_part = (By.XPATH, '//a[contains(., "Внести результаты")]')
    save_success = (By.XPATH, '//button[contains(., "Успешно сохранено")]')
    btn_all_redpoints = (By.ID, 'all-redpoint')
    btn_send_result = (By.ID, 'btn-send-result')
    success_take_part_2 = (By.XPATH, '//button[contains(., "Вы принимаете участие")]')
